# Generated by Django 5.0.4 on 2024-11-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_company_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='current_employee_estimate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='total_employee_estimate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='year_founded',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
